# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from encryptDialog import Ui_encrypt
from decryptDialog import Ui_decrypt

class Ui_file1(object):
        def encryptWindow(self):
                self.window= QtWidgets.QDialog()
                self.ui = Ui_encrypt()
                self.ui.setupUi(self.window)
                self.window.show()
        def decryptWindow(self):
                self.window= QtWidgets.QDialog()
                self.ui = Ui_decrypt()
                self.ui.setupUi(self.window)
                self.window.show()
        def setupUi(self, file1):
                file1.setObjectName("file1")
                file1.resize(560, 429)
                file1.setStyleSheet("background-color:rgb(255, 239, 255)")
                self.frame = QtWidgets.QFrame(file1)
                self.frame.setGeometry(QtCore.QRect(-60, -10, 621, 101))
                self.frame.setMinimumSize(QtCore.QSize(421, 0))
                self.frame.setStyleSheet("background-color:rgb(0, 0, 74)")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.fontLabel_2 = QtWidgets.QLabel(self.frame)
                self.fontLabel_2.setGeometry(QtCore.QRect(80, 20, 531, 71))
                font = QtGui.QFont()
                font.setFamily("Showcard Gothic")
                font.setPointSize(48)
                font.setBold(False)
                font.setWeight(50)
                self.fontLabel_2.setFont(font)
                self.fontLabel_2.setStyleSheet("#fontLabel {\n"
                "    color: RED;\n"
                "}")
                self.fontLabel_2.setObjectName("fontLabel_2")
                self.encryptButton = QtWidgets.QPushButton(file1)
                self.encryptButton.setGeometry(QtCore.QRect(190, 160, 171, 51))
                self.encryptButton.setStyleSheet("#encryptButton {\n"
                "    font: 14pt \"MS Shell Dlg 2\";\n"
                "    border: 2px solid #1976D2;\n"
                "    background-color:rgb(0, 0, 127);\n"
                "    min-width: 80px;\n"
                "    color: white;\n"
                "}\n"
                "#encryptButton:hover {\n"
                "    background-color:rgb(164, 255, 167);\n"
                "    \n"
                "}\n"
                "\n"
                "#encryptButton:pressed {\n"
                "    background-color: #0D47A1;\n"
                "}\n"
                "\n"
                "#encryptButton:flat {\n"
                "    border: none; /* no border for a flat push button */\n"
                "}\n"
                "\n"
                "#encryptButton:default {\n"
                "    border-color: white; /* make the default button prominent */\n"
                "}\n"
                "\n"
                "#encryptButton:disabled {\n"
                "    background-color: #E3F2FD;\n"
                "    border-color: #BBDEFB;\n"
                "}")
                self.encryptButton.setObjectName("encryptButton")
                self.encryptButton.clicked.connect(self.encryptWindow)
                self.decryptButton = QtWidgets.QPushButton(file1)
                self.decryptButton.setGeometry(QtCore.QRect(190, 260, 171, 51))
                self.decryptButton.setStyleSheet("#decryptButton {\n"
                "    font: 14pt \"MS Shell Dlg 2\";\n"
                "    border: 2px solid #1976D2;\n"
                "    background-color:rgb(0, 0, 127);\n"
                "    min-width: 80px;\n"
                "    color: white;\n"
                "}\n"
                "#decryptButton:hover {\n"
                "    background-color:rgb(164, 255, 167);\n"
                "    \n"
                "}\n"
                "\n"
                "#decryptButton:pressed {\n"
                "    background-color: #0D47A1;\n"
                "}\n"
                "\n"
                "#decryptButton:flat {\n"
                "    border: none; /* no border for a flat push button */\n"
                "}\n"
                "\n"
                "#decryptButton:default {\n"
                "    border-color: white; /* make the default button prominent */\n"
                "}\n"
                "\n"
                "#decryptButton:disabled {\n"
                "    background-color: #E3F2FD;\n"
                "    border-color: #BBDEFB;\n"
                "}")
                self.decryptButton.setObjectName("decryptButton")
                self.decryptButton.clicked.connect(self.decryptWindow)
                self.label = QtWidgets.QLabel(file1)
                self.label.setGeometry(QtCore.QRect(90, 100, 381, 31))
                self.label.setObjectName("label")

                self.retranslateUi(file1)
                QtCore.QMetaObject.connectSlotsByName(file1)

        def retranslateUi(self, file1):
                _translate = QtCore.QCoreApplication.translate
                file1.setWindowTitle(_translate("file1", "File Enrypter"))
                self.frame.setToolTip(_translate("file1", "<html><head/><body><p><img src=\":/Images/lock.jpg\"/></p></body></html>"))
                self.frame.setWhatsThis(_translate("file1", "<html><head/><body><p><img src=\":/Images/lock.jpg\"/></p></body></html>"))
                self.fontLabel_2.setToolTip(_translate("file1", "<html><head/><body><p>LK</p></body></html>"))
                self.fontLabel_2.setText(_translate("file1", "<html><head/><body><p><span style=\" font-size:36pt; color:#ffaa00;\">file encryptor</span></p></body></html>"))
                self.encryptButton.setText(_translate("file1", "ENCRYPT"))
                self.decryptButton.setText(_translate("file1", "DECRYPT"))
                self.label.setText(_translate("file1", "<html><head/><body><p><span style=\" font-size:12pt; color:#ff0000;\">Choose the function you want to perform:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    file1 = QtWidgets.QDialog()
    ui = Ui_file1()
    ui.setupUi(file1)
    file1.show()
    sys.exit(app.exec_())

